version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: dhr-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=dhr-cluster
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - dhr-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: dhr-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server/src:/app/src
      - ./server/logs:/app/logs
      - /app/node_modules
    networks:
      - dhr-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: dhr-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - /app/node_modules
    networks:
      - dhr-network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: dhr-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    networks:
      - dhr-network
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  dhr-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local