apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhr-backend
  namespace: default
  labels:
    app: dhr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhr-backend
  template:
    metadata:
      labels:
        app: dhr-backend
    spec:
      containers:
      - name: dhr-backend
        image: dhr-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch:9200"
        # Authentication disabled for local Elasticsearch
        # - name: ELASTICSEARCH_USERNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: dhr-config
        #       key: elasticsearch-username
        # - name: ELASTICSEARCH_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: dhr-secrets
        #       key: elasticsearch-password
        - name: ALLOWED_HEALTH_INDEXES
          valueFrom:
            configMapKeyRef:
              name: dhr-config
              key: allowed-health-indexes
        - name: PROJECT_INDEX_MAPPING
          valueFrom:
            configMapKeyRef:
              name: dhr-config
              key: project-index-mapping
        - name: CORS_ORIGINS
          value: "*"
        - name: LOG_LEVEL
          value: "info"
        - name: SKIP_ELASTICSEARCH_HEALTH_CHECK
          value: "true"
# Health checks temporarily disabled - need to add /health endpoint
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"