apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhr-frontend
  namespace: default
  labels:
    app: dhr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhr-frontend
  template:
    metadata:
      labels:
        app: dhr-frontend
    spec:
      containers:
      - name: dhr-frontend
        image: dhr-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: dhr-frontend
  namespace: default
  labels:
    app: dhr-frontend
spec:
  selector:
    app: dhr-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dhr-frontend-nodeport
  namespace: default
  labels:
    app: dhr-frontend
spec:
  selector:
    app: dhr-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  type: NodePort