apiVersion: v1
kind: Service
metadata:
  name: dhr-backend
  namespace: default
  labels:
    app: dhr-backend
spec:
  selector:
    app: dhr-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dhr-backend-nodeport
  namespace: default
  labels:
    app: dhr-backend
spec:
  selector:
    app: dhr-backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
    name: http
  type: NodePort